# 1 - Tensor operations

In [1]:
import torch

In [2]:
torch.__version__

'1.3.1'

## 1.1 - Creation

In [3]:
# Tensor based on another
torch.FloatTensor([[3,2],[1,4]])

tensor([[3., 2.],
        [1., 4.]])

In [4]:
# Identity
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [5]:
# Tensor with ones
torch.ones(3, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
# Tensor with zeros
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [7]:
# Ones like
a = torch.eye(3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
a = torch.LongTensor([3,2])
a

tensor([3, 2])

In [9]:
a.float()

tensor([3., 2.])

In [10]:
# Range
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [11]:
# Multiplication by a scalar
torch.eye(3) * 3 

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [12]:
# Adding two tensors
torch.eye(3) + torch.ones(3)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

### Exercise: 
Create a 4x4 tensor with 0.5 on each cell, and 4 in the diagonal

In [13]:
torch.FloatTensor([[4, 0.5, 0.5, 0.5],
                   [0.5, 4, 0.5, 0.5],
                   [0.5, 0.5, 4, 0.5],
                   [0.5, 0.5, 0.5, 4]])

tensor([[4.0000, 0.5000, 0.5000, 0.5000],
        [0.5000, 4.0000, 0.5000, 0.5000],
        [0.5000, 0.5000, 4.0000, 0.5000],
        [0.5000, 0.5000, 0.5000, 4.0000]])

In [14]:
torch.eye(4) * 3.5 + torch.ones(4, 4) * 0.5

tensor([[4.0000, 0.5000, 0.5000, 0.5000],
        [0.5000, 4.0000, 0.5000, 0.5000],
        [0.5000, 0.5000, 4.0000, 0.5000],
        [0.5000, 0.5000, 0.5000, 4.0000]])

In [15]:
torch.eye(4) * 3.5 + 0.5

tensor([[4.0000, 0.5000, 0.5000, 0.5000],
        [0.5000, 4.0000, 0.5000, 0.5000],
        [0.5000, 0.5000, 4.0000, 0.5000],
        [0.5000, 0.5000, 0.5000, 4.0000]])

# 1.2 - Manipulating tensors

### Selecting data

In [16]:
x = torch.eye(4)
x

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [17]:
x[2,2]

tensor(1.)

In [18]:
x[0:2,0:2]

tensor([[1., 0.],
        [0., 1.]])

### Assigning values

In [19]:
x[0,0] = 4
x

tensor([[4., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### Exercise: 

Set the top left 2x2 square of x to:

[2, 3]
[4, 5]



In [20]:
x

tensor([[4., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [21]:
x[0, 0] = 2
x[0,1] = 3
x[1,0] = 4
x[1,1] = 5
x

tensor([[2., 3., 0., 0.],
        [4., 5., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [22]:
x[0:2, 0:2] = torch.FloatTensor([[2,3], [4,5]])
x

tensor([[2., 3., 0., 0.],
        [4., 5., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### Concatenate

In [23]:
x = torch.eye(4)
x

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [24]:
torch.cat([x, x, x], dim=0)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [25]:
torch.cat([x, x, x], dim=1)

tensor([[1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.]])

### Adding dimensions

In [26]:
x = torch.eye(4)
x

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [27]:
x.shape

torch.Size([4, 4])

In [28]:
y = torch.unsqueeze(x, 0)
y

tensor([[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]])

In [29]:
y.shape

torch.Size([1, 4, 4])

### Remove dimensions

In [30]:
z = torch.squeeze(y, 0)
z

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [31]:
z.shape

torch.Size([4, 4])

### Element wise multiplication

In [32]:
x = torch.eye(3)*3
y = torch.eye(3)*2
x * y

tensor([[6., 0., 0.],
        [0., 6., 0.],
        [0., 0., 6.]])

### Matrix multiplication

In [33]:
x = torch.LongTensor([[2, 1, 0],[3,2,1]])
y = torch.LongTensor([1,1])
x.shape, y.shape

(torch.Size([2, 3]), torch.Size([2]))

In [34]:
torch.matmul( x.transpose(0,1), y)

tensor([5, 3, 1])

### Broadcasting

In [35]:
x = torch.rand(4,1)
y = torch.rand(1,5)

In [36]:
x

tensor([[0.0950],
        [0.7775],
        [0.3699],
        [0.5114]])

In [37]:
y

tensor([[0.5705, 0.3654, 0.6792, 0.4199, 0.1514]])

In [38]:
(x * y).shape

torch.Size([4, 5])

In [39]:
x = torch.rand(5,1,4,1)
y = torch.rand(  3,1,1)
(x * y).shape

torch.Size([5, 3, 4, 1])

### Changing Dimensions

In [40]:
x.shape

torch.Size([5, 1, 4, 1])

In [41]:
# Check it out by yourself!
x

tensor([[[[0.3838],
          [0.5325],
          [0.3450],
          [0.9989]]],


        [[[0.2496],
          [0.5791],
          [0.2711],
          [0.9331]]],


        [[[0.9470],
          [0.3226],
          [0.7334],
          [0.2092]]],


        [[[0.0318],
          [0.7159],
          [0.6720],
          [0.6224]]],


        [[[0.8990],
          [0.3851],
          [0.1276],
          [0.4674]]]])

In [42]:
x.view(5,4).shape

torch.Size([5, 4])

In [43]:
x.view(5,4)

tensor([[0.3838, 0.5325, 0.3450, 0.9989],
        [0.2496, 0.5791, 0.2711, 0.9331],
        [0.9470, 0.3226, 0.7334, 0.2092],
        [0.0318, 0.7159, 0.6720, 0.6224],
        [0.8990, 0.3851, 0.1276, 0.4674]])

In [44]:
x.view(20).shape

torch.Size([20])

In [45]:
x.view(20)

tensor([0.3838, 0.5325, 0.3450, 0.9989, 0.2496, 0.5791, 0.2711, 0.9331, 0.9470,
        0.3226, 0.7334, 0.2092, 0.0318, 0.7159, 0.6720, 0.6224, 0.8990, 0.3851,
        0.1276, 0.4674])

In [46]:
# Use -1 as your trump card (fills with the values that is lacking)
x.view(-1).shape

torch.Size([20])

In [47]:
x.view(4,-1).shape

torch.Size([4, 5])

### Mathematical Operations

In [48]:
x = torch.FloatTensor([[3, -2], [-1, 2]])
torch.abs(x)

tensor([[3., 2.],
        [1., 2.]])

In [49]:
torch.exp(x)

tensor([[20.0855,  0.1353],
        [ 0.3679,  7.3891]])

In [50]:
torch.cos(x)

tensor([[-0.9900, -0.4161],
        [ 0.5403, -0.4161]])

### Create your own sigmoid function!

![sigmoid](https://wikimedia.org/api/rest_v1/media/math/render/svg/b9db8cd0955e7898d6556581941581e3c7522f51)

In [51]:
# Exercise: Build sigmoid function

def sigm(x):
    return 1 / (1 + torch.exp(-x))

In [52]:
x = torch.FloatTensor([1,2,3])

In [53]:
sigm(x)

tensor([0.7311, 0.8808, 0.9526])

In [54]:
def softmax(x):
    return torch.exp(x) / torch.exp(x).sum(-1)

In [55]:
torch.sigmoid(x)

tensor([0.7311, 0.8808, 0.9526])

### Exercise: build the mean squared error loss function

In [56]:
y = torch.FloatTensor([1,2,3,4])
y_hat = torch.FloatTensor([2,0,3,4])

In [57]:
# Exercise: build the mean squared error loss function (note tensor.mean() will provide the mean of a tensor)
def mse_loss(y, y_hat):
    return torch.mean((y - y_hat) ** 2)

In [58]:
mse_loss(torch.FloatTensor([1, 2, 3]),
         torch.FloatTensor([1, 2, 4]))

tensor(0.3333)

In [59]:
# Using Torch functions
import torch.nn.functional as F
F.mse_loss(torch.FloatTensor([1., 2., 3.]),
           torch.FloatTensor([1., 2., 4.]))

tensor(0.3333)

In [60]:
# Exercise: imagine you have:
y = torch.FloatTensor([[2],[1],[0.3],[0.3]])
# and
y_hat = torch.FloatTensor([[2,1,0.3,0.3]])
# with shapes:
y.shape, y_hat.shape

(torch.Size([4, 1]), torch.Size([1, 4]))

In [61]:
# Problems with broadcasting
y - y_hat

tensor([[ 0.0000,  1.0000,  1.7000,  1.7000],
        [-1.0000,  0.0000,  0.7000,  0.7000],
        [-1.7000, -0.7000,  0.0000,  0.0000],
        [-1.7000, -0.7000,  0.0000,  0.0000]])

In [62]:
# Why is the mse not 0?
# How can we fix it?
mse_loss(y, y_hat)

tensor(0.9700)

In [63]:
# squeeze
y.squeeze()

tensor([2.0000, 1.0000, 0.3000, 0.3000])

In [64]:
y_hat.squeeze()

tensor([2.0000, 1.0000, 0.3000, 0.3000])

In [65]:
mse_loss(y.squeeze(), y_hat.squeeze())

tensor(0.)

# Simplest Neural network Layer 

In [66]:
import torch.nn as nn
import torch.nn.functional as F

In [67]:
x = torch.rand(5)

In [68]:
layer = nn.Linear(in_features=5, out_features=2)

In [69]:
# Check the layer weights
layer.weight

Parameter containing:
tensor([[ 0.1386,  0.2707,  0.2472,  0.3390,  0.3414],
        [-0.3132,  0.1567,  0.0901, -0.4465,  0.4050]], requires_grad=True)

In [70]:
(layer.weight).shape

torch.Size([2, 5])

In [71]:
# Check the layer bias
layer.bias

Parameter containing:
tensor([-0.2337, -0.3355], requires_grad=True)

In [72]:
(layer.bias).shape 

torch.Size([2])

In [73]:
x

tensor([0.7444, 0.7954, 0.1846, 0.5613, 0.1680])

In [74]:
layer(x)

tensor([ 0.3780, -0.6100], grad_fn=<AddBackward0>)

In [75]:
# Apply any activation function (i.e. RELU, softmax, tanh...)
F.relu(layer(x))

tensor([0.3780, 0.0000], grad_fn=<ReluBackward0>)